using Newtonsoft.Json;

namespace PersonalCapital.Response;

public record UpdateTransactionResponseData(
    [property: JsonProperty("symbol")] string Symbol,
    [property: JsonProperty("isInterest")] bool IsInterest,
    [property: JsonProperty("netCost")] double NetCost,
    [property: JsonProperty("cusipNumber")] string CusipNumber,
    [property: JsonProperty("accountName")] string AccountName,
    [property: JsonProperty("description")] string Description,
    [property: JsonProperty("memo")] string Memo,
    [property: JsonProperty("isCredit")] bool IsCredit,
    [property: JsonProperty("customTags")] CustomTags CustomTags,
    [property: JsonProperty("isEditable")] bool IsEditable,
    [property: JsonProperty("isCashOut")] bool IsCashOut,
    [property: JsonProperty("merchantId")] string MerchantId,
    [property: JsonProperty("price")] double Price,
    [property: JsonProperty("holdingType")] string HoldingType,
    [property: JsonProperty("lotHandling")] string LotHandling,
    [property: JsonProperty("customReason")] string CustomReason,
    [property: JsonProperty("hasSplits")] bool HasSplits,
    [property: JsonProperty("userTransactionId")] long UserTransactionId,
    [property: JsonProperty("currency")] string Currency,
    [property: JsonProperty("isDuplicate")] bool IsDuplicate,
    [property: JsonProperty("resultType")] string ResultType,
    [property: JsonProperty("originalDescription")] string OriginalDescription,
    [property: JsonProperty("isSpending")] bool IsSpending,
    [property: JsonProperty("amount")] double Amount,
    [property: JsonProperty("checkNumber")] string CheckNumber,
    [property: JsonProperty("transactionTypeId")] int TransactionTypeId,
    [property: JsonProperty("isIncome")] bool IsIncome,
    [property: JsonProperty("includeInCashManager")] bool IncludeInCashManager,
    [property: JsonProperty("merchant")] string Merchant,
    [property: JsonProperty("isNew")] bool IsNew,
    [property: JsonProperty("isCashIn")] bool IsCashIn,
    [property: JsonProperty("transactionDate")] string TransactionDate,
    [property: JsonProperty("transactionType")] string TransactionType,
    [property: JsonProperty("accountId")] string AccountId,
    [property: JsonProperty("originalAmount")] double OriginalAmount,
    [property: JsonProperty("isCost")] bool IsCost,
    [property: JsonProperty("userAccountId")] int UserAccountId,
    [property: JsonProperty("simpleDescription")] string SimpleDescription,
    [property: JsonProperty("runningBalance")] double RunningBalance,
    [property: JsonProperty("hasViewed")] bool HasViewed,
    [property: JsonProperty("categoryId")] int CategoryId,
    [property: JsonProperty("status")] string Status
);
